remote_theme: mmistakes/minimal-mistakes

# To change skin, go into assets/css/main.scss

locale: "en-US"

title: "Neuton Foo"
title_separator: "|"

name: "Neuton Foo"
repository: "neutonfoo/neutonfoo.github.io"

breadcrumbs: true

head_scripts:
  - https://code.jquery.com/jquery-3.3.1.min.js

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-107705769-4"
    anonymize_ip: false # default

author:
  name: "Neuton Foo"
  email: "nfoo@usc.edu"
  github: "neutonfoo"
  linkedin: "neutonfoo"
